#ifndef FUZZFLOW_NODES_H
#define FUZZFLOW_NODES_H

#include "../nodes/BeginNode.h"
#include "../nodes/BinaryOpNode.h"
#include "../nodes/LiteralNode.h"
#include "../nodes/LiteralBoolNode.h"
#include "../nodes/LiteralFloatNode.h"
#include "../nodes/LiteralStringNode.h"
#include "../nodes/CtrlRelayNode.h"
#include "../nodes/EndNode.h"
#include "../nodes/EndProgramNode.h"

#include "../nodes/FunctionHeadNode.h"
#include "../nodes/GlobalVarNode.h"
#include "../nodes/GlobalFunctionNode.h"
#include "../nodes/IfNode.h"
#include "../nodes/InvokeMethodNode.h"
#include "../nodes/InvokeNode.h"
#include "../nodes/LoopBegin.h"
#include "../nodes/LoopEnd.h"
#include "../nodes/LoopExit.h"
#include "../nodes/LoopIf.h"
#include "../nodes/MergeNode.h"
#include "../nodes/ParameterNode.h"
#include "../nodes/PhiNode.h"
#include "../nodes/ReturnNode.h"
#include "../nodes/TerminalNode.h"
#include "../nodes/TernaryOpNode.h"
#include "../nodes/UnaryOpNode.h"
#include "../nodes/UniSuccessorNode.h"

#include "../nodes/FakeCtrlNode.h"
#include "../nodes/FixedNode.h"
#include "../nodes/IRNode.h"

#include "../nodes/js/AccessObjectNode.h"
#include "../nodes/js/ArrayLiteralNode.h"
#include "../nodes/js/BuiltinNode.h"
#include "../nodes/js/CatchIdNode.h"
#include "../nodes/js/CatchNode.h"
#include "../nodes/js/ComputedPropExprAssignNode.h"
#include "../nodes/js/DeleteNode.h"
#include "../nodes/js/FinallyNode.h"
#include "../nodes/js/ForInEnum.h"
#include "../nodes/js/ForInPropName.h"
#include "../nodes/js/FunctionPropertyNode.h"
#include "../nodes/js/LoadNode.h"
#include "../nodes/js/ObjectLiteralNode.h"
#include "../nodes/js/PropExprAssignNode.h"
#include "../nodes/js/StoreNode.h"
#include "../nodes/js/ThisNode.h"
#include "../nodes/js/TryExit.h"
#include "../nodes/js/TryNode.h"
#include "../nodes/js/UnwindNode.h"

#endif //FUZZFLOW_NODES_H
