#include "JavaScriptLifter.h"

#include "../js2graph/OperatorPairs.h"
#include "../nodes/AllNodesInclude.h"

namespace FuzzFlow {

void JavaScriptLifter::build_node2varProxy(const map<shared_ptr<VarProxy>,
                                                     weak_ptr<DataProducerNode>>& varProxy2node)
{
    for (auto& [_proxy, _node] : varProxy2node) {
        if (! this->node2varProxy.contains(_node)) {
            this->node2varProxy.insert({_node, {_proxy}});
        }
        else {
            this->node2varProxy[_node].push_back(_proxy);
        }
    }

    if (! graph->splice_graph_varProxy2node.empty()) {
        for (auto& [_proxy, _node] : graph->splice_graph_varProxy2node) {
            if (! this->node2varProxy.contains(_node)) {
                this->node2varProxy.insert({_node, {_proxy}});
            }
            else {
                this->node2varProxy[_node].push_back(_proxy);
            }
        }
    }
}

vector<shared_ptr<VarSymbol>> JavaScriptLifter::get_varSymbols_on_producer(const weak_ptr<DataProducerNode>& producer)
{
    vector<shared_ptr<VarSymbol>> var_syms;

    if (this->node2varProxy.contains(producer))
    {
        for (const auto& _proxy : this->node2varProxy[producer]) {
            var_syms.push_back(_proxy->var_symbol);
        }
    }

    return var_syms;
}

vector<shared_ptr<VarProxy>> JavaScriptLifter::get_varProxies_on_producer(const weak_ptr<DataProducerNode>& producer)
{
    vector<shared_ptr<VarProxy>> var_proxies;

    if (this->node2varProxy.contains(producer))
    {
        for (const auto& _proxy : this->node2varProxy[producer]) {
            var_proxies.push_back(_proxy);
        }
    }

    return var_proxies;
}

void JavaScriptLifter::update_varSymbol2Regions(vector<shared_ptr<VarSymbol>>& var_syms)
{
    const weak_ptr<Region> region = this->current_region_single;

    for (auto& var_sym : var_syms)
    {
        if (auto regions_pos = this->varSymbol2Regions.find(var_sym);
            regions_pos != this->varSymbol2Regions.end())
        {
            auto& regions = regions_pos->second;
            regions.insert(region);
        }
        else {
            set<weak_ptr<Region>, std::owner_less<>> regions = {region};
            this->varSymbol2Regions.insert({{var_sym, regions}});
        }
    }
}

/// If a `var proxy` is attached to a data producer node, record the corresponding assignment's generated `regionNested`.
/// Note: `regionNested` may not be within the scope of its later uses.
/// If it's not found in the parent chain of `Region` during later processing, the assignment must be regenerated.
///
void JavaScriptLifter::update_region2varProxies(const weak_ptr<DataProducerNode>& node)
{
    vector<shared_ptr<VarProxy>> node_var_proxies = this->get_varProxies_on_producer(node);

    weak_ptr<const RegionNested> region = this->current_region_single->parent_region;

    auto pos = this->region2varProxies.find(region);

    if (pos != this->region2varProxies.end()) {
        auto& proxies = pos->second;

        for (auto& var_proxy : node_var_proxies) {
            proxies.push_back(var_proxy);
        }
    }
    else {
        vector<shared_ptr<VarProxy>> proxies;
        for (auto& var_proxy : node_var_proxies) {
            proxies.push_back(var_proxy);
        }
        this->region2varProxies.insert({{region, proxies}});
    }
}

void JavaScriptLifter::check_region_single()
{
    if (this->current_region_single == nullptr)
    {
        this->current_region_single = make_shared<RegionSingle>();
        this->current_parent_region->add_region(this->current_region_single);
    }
}

/// Check whether a var symbol has been assigned within the accessible scope (current or any outer regions).
bool JavaScriptLifter::varProxy_reach_current_region(const shared_ptr<VarProxy> &var_proxy)
{
    weak_ptr<const RegionNested> region_nested = this->current_region_single->parent_region;

    bool varProxyAlreadyAvailable = false;
    bool has_shadowed_variable = false;

    while (region_nested.lock() != nullptr)
    {
        if (this->region2varProxies.contains(region_nested))
        {
            auto assigned_proxies = this->region2varProxies[region_nested];

            const vector<shared_ptr<VarProxy>> proxies_v (assigned_proxies.begin(),assigned_proxies.end());

            /// Search in reverse order because the later proxy is generated by a subsequent assignment,
            /// making it closer to the current position.
            for (int i = assigned_proxies.size() - 1; i >= 0; i--) {
                if (assigned_proxies[i] == var_proxy) {
                    varProxyAlreadyAvailable = true;
                    break;
                }

                /// If the execution reaches this point, it means the current proxy i is not the target var proxy we are looking for.
                /// However, if their names are the same, it indicates an identifier naming conflict, and proxy i interferes with the
                /// data flow of var proxy. In such a case, the assignment statement for var proxy should be regenerated.
                if (assigned_proxies[i]->var_symbol->name == var_proxy->var_symbol->name)
                {
                    weak_ptr<DataProducerNode> node_1;
                    if (this->graph->varProxy2node.contains(assigned_proxies[i])) {
                        node_1 = this->graph->varProxy2node.at(assigned_proxies[i]);
                    }

                    weak_ptr<DataProducerNode> node_2;
                    if (this->graph->varProxy2node.contains(var_proxy)) {
                        node_2 = this->graph->varProxy2node.at(var_proxy);
                    }

                    if ((! node_1.expired())
                        && (! node_2.expired())
                        && node_1.lock() == node_2.lock())
                    {
                        /// If the two proxies are different but reference the same node,
                        /// this does not correspond to the case where a variable with the same name exists in the reachable scope.
                        continue;
                    }

                    has_shadowed_variable = true;
                    break;
                }
            }
        }

        if (has_shadowed_variable) {
            break;
        }

        region_nested = region_nested.lock()->parent_region.lock();
    }

    return varProxyAlreadyAvailable;
}

/// A data producer node may have multiple attached var proxies.
/// Check whether all corresponding `var` symbols are assigned within the current scope.
///
bool JavaScriptLifter::all_varProxy_available(const weak_ptr<DataProducerNode>& node)
{
    vector<shared_ptr<VarProxy>> var_proxies = this->get_varProxies_on_producer(node);

    /// Check whether all var symbols attached to the node have been assigned within the current scope.
    bool all_assigned = true;

    for (const auto& var_proxy : var_proxies) {

        if (const bool has_assigned = this->varProxy_reach_current_region(var_proxy);
            ! has_assigned)
        {
            all_assigned = false;
            break;
        }
    }

    return all_assigned;
}

void JavaScriptLifter::gen_assignment_for_producer(const weak_ptr<DataProducerNode>& producer,
                                                   const string &assign_expr,
                                                   const  bool self_assignment)
{
    vector<shared_ptr<VarSymbol>> var_syms = this->get_varSymbols_on_producer(producer);

    if (var_syms.empty()) {
        return;
    }

    /// Maintain the mapping between var symbols and regions in preparation for generating declaration statements.
    this->update_varSymbol2Regions(var_syms);

    /// Maintain the mapping between regions and var proxies to determine whether an assignment statement should be
    /// generated when revisiting this data producer.
    this->update_region2varProxies(producer);

    /// This on-demand generation approach may place the assignment in a lower scope level,
    /// which can lead to the variable being out of scope when it's needed later.
    ///
    const shared_ptr<RegionSingle> region = this->current_region_single;
    region->emit_assignment(var_syms, assign_expr, self_assignment);
}

uint32_t JavaScriptLifter::lift()
{
    const shared_ptr<FunctionHeadNode> function_head = dynamic_pointer_cast<FunctionHeadNode>(this->graph->nodes[0]);

    assert_or_throw_graph2js((function_head != nullptr),
        "The first node in graph nodes should be FunctionHeadNode");

    const auto region_single = make_shared<RegionSingle>();
    this->current_region_single = region_single;
    this->current_parent_region->add_region(region_single);

    this->function_name = function_head->get_label();

    for (auto& param_node : function_head->get_params())
    {
        /// Function parameters should not be handled on demand during the lift process,
        /// as this may lead to inconsistent parameter order and argument mismatches when multiple parameters are involved.
        /// Here, function parameters are processed separately by recording their names in `function args`,
        /// so that lifting to a `TerminalNode` only needs to return the parameter name.
        ///
        this->function_args.push_back(param_node.lock()->get_parameter_name());

        /// function args can be seen as declared variables
        vector<shared_ptr<VarSymbol>> var_symbols = this->get_varSymbols_on_producer(param_node);
    }

    /// traverse begin

    this->in_edge_stack.push(InEdgeType::Ctrl);
    function_head->next()->accept(*this);
    this->in_edge_stack.pop();

    /// traverse finished

    /// Generate declarations for variables
    for (auto& [var_sym, regions] : this->varSymbol2Regions) {
        /// For each var symbol, identify all `Region`s where it appears and compute their lowest common ancestor (`RegionNested`).
        /// The first encountered `regionSingle` is chosen as the declaration location.
        auto mini_parent = Region::get_mini_parent_region(regions);

        shared_ptr<RegionSingle> _region = dynamic_pointer_cast<RegionSingle>(mini_parent.lock()->get_first_region());

        assert_or_throw_graph2js((_region != nullptr),
            "The first region in region nested is RegionSingle");

        _region->emit_var_declaration(var_sym);
    }

    return visited_nodes_num;
}

void JavaScriptLifter::visit(shared_ptr<LoopEnd> &node)
{
    //if (auto loop_begin = dynamic_pointer_cast<LoopBegin>(node->merge_node.lock())) {
    //    this->set_merge_node(loop_begin);
    //}
}

void JavaScriptLifter::visit(shared_ptr<EndNode> &node)
{
    if (auto loop_begin = dynamic_pointer_cast<LoopBegin>(node->merge_node.lock())) {
        this->in_edge_stack.push(InEdgeType::Ctrl);
        loop_begin->accept(*this);
        this->in_edge_stack.pop();
    }
    else if (auto merge_node = dynamic_pointer_cast<MergeNode>(node->merge_node.lock())) {
        /// When a `MergeNode` is encountered, it indicates the end of a branch.
        /// Return the MergeNode to the lift IfNode function.
        this->set_merge_node(merge_node);
    }
    else if (auto relay_node = dynamic_pointer_cast<CtrlRelayNode>(node->merge_node.lock())) {
        /// When a control relay node is encountered, it means only one branch of the if-else continues.
        /// Return the relay node to the lift IfNode function.
        this->set_relay_node(relay_node);
    }
    else {
        /// try end + catch end + finally
    }
}

///
/// If a PhiNode contains multiple var proxies, query the merged dataflow sources
/// to find the corresponding var proxy. The common var symbol between phi's two
/// inputs represents the actual merged dataflow variable. We call its proxy on
/// the phi node the "main var proxy".
///
/// During lifting:
/// 1. This main var proxy should be returned
/// 2. Other var proxies attached to the phi node should be assigned from it
///
shared_ptr<VarSymbol> JavaScriptLifter::get_phi_main_proxy(const weak_ptr<PhiNode>& phi_node_w)
{
    auto phi_node = phi_node_w.lock();

    vector<shared_ptr<VarSymbol>> var_sym_1 = this->get_varSymbols_on_producer(phi_node->get_input(0));
    this->update_varSymbol2Regions(var_sym_1);
    if (var_sym_1.size() == 1) {
        shared_ptr<VarSymbol> var_sym = var_sym_1[0];
        return var_sym;
    }

    vector<shared_ptr<VarSymbol>> var_sym_2 = this->get_varSymbols_on_producer(phi_node->get_input(1));
    this->update_varSymbol2Regions(var_sym_2);
    if (var_sym_2.size() == 1) {
        shared_ptr<VarSymbol> var_sym = var_sym_2[0];
        return var_sym;
    }

    std::sort(var_sym_1.begin(), var_sym_1.end());
    std::sort(var_sym_2.begin(), var_sym_2.end());

    /// If both input nodes have multiple var proxies, try to find the single common proxy between them.
    vector<shared_ptr<VarSymbol>> var_sym_intersection;
    std::set_intersection(var_sym_1.begin(), var_sym_1.end(),
                          var_sym_2.begin(), var_sym_2.end(),
                          std::back_inserter(var_sym_intersection));

    if (var_sym_intersection.size() == 1) {
        return var_sym_intersection[0];
    }

    assert_or_throw_graph2js(false,
        "Failed to decide the main proxy for phi node");
    return nullptr;
}

/**
 * There are two types of loop: while mode and for-in mode.
 * While mode contains loops of while, and normal for loop.
 */
void JavaScriptLifter::visit(shared_ptr<LoopBegin> &node)
{
    shared_ptr<LoopIf> loop_if_node;
    shared_ptr<ForInEnum> for_in_enum_node;

    bool while_loop_mode = false;
    bool for_in_loop_mode = false;

    if (! node->loop_if.expired()) {
        loop_if_node = node->loop_if.lock();
        while_loop_mode = true;
    }

    if (! node->loop_forin.expired()) {
        for_in_enum_node = node->loop_forin.lock();
        for_in_loop_mode = true;
    }

    if (((while_loop_mode == false) && (for_in_loop_mode == false))
        || ((while_loop_mode == true) && (for_in_loop_mode == true)))
    {
        throw LiftError("Unknown loop mode");
    }

    LoopMode loop_mode = while_loop_mode ? LoopMode::WHILE : LoopMode::FORIN;
    const auto region_loop = make_shared<RegionLoopBegin>(loop_mode);

    /// First, set the parent of RegionLoopBegin, and then invoke its post construct
    this->current_parent_region->add_region(region_loop);
    region_loop->post_construct();

    /// log the previous parent region
    auto parent_region = this->current_parent_region;

    for (auto phi_node : node->phi_nodes()) {
        this->current_region_single = region_loop->loop_before;

        /// Implicitly assumes that for a LoopBegin node's phi, the first input comes from before the loop,
        /// and the second input comes from within the loop.
        auto node = phi_node.lock()->get_input(0);

        this->in_edge_stack.push(InEdgeType::Data);
        node->accept(*this);
        this->in_edge_stack.pop();
    }

    /// Traverse loop condition
    /// Generate the newly produced assignment into the loop fate before region
    this->current_region_single = region_loop->loop_fake_before;
    if (loop_mode == LoopMode::WHILE) {
        this->in_edge_stack.push(InEdgeType::Data);
        loop_if_node->condition()->accept(*this);
        this->in_edge_stack.pop();

        const string condition_expr = visit_outcome;

        region_loop->loop_condition->emit_expression(condition_expr);
    }
    else {
        this->in_edge_stack.push(InEdgeType::Data);
        for_in_enum_node->enumPropName()->accept(*this);
        this->in_edge_stack.pop();

        const string prop_name = visit_outcome;

        this->in_edge_stack.push(InEdgeType::Data);
        for_in_enum_node->enumObject()->accept(*this);
        this->in_edge_stack.pop();

        const string object_name = visit_outcome;

        region_loop->loop_condition->emit_expression("let " + prop_name + " in " + object_name);
    }

    /// Traverse loop body
    this->current_parent_region = region_loop->loop_body;

    auto region_single_in_body = make_shared<RegionSingle>();
    this->current_region_single = region_single_in_body;
    this->current_parent_region->add_region(region_single_in_body);

    if (loop_mode == LoopMode::WHILE) {
        this->in_edge_stack.push(InEdgeType::Ctrl);
        loop_if_node->branch_true()->accept(*this);
        this->in_edge_stack.pop();
    }
    else {
        this->in_edge_stack.push(InEdgeType::Ctrl);
        for_in_enum_node->branch_true()->accept(*this);
        this->in_edge_stack.pop();
    }

    /// restore parent region
    this->current_parent_region = parent_region;

    /// traverse the second input (data flow in the loop body) of phi nodes
    for (auto phi_node : node->phi_nodes()) {
        this->current_region_single = region_loop->loop_body_tail;
        auto _node = phi_node.lock()->get_input(1);

        this->in_edge_stack.push(InEdgeType::Data);
        _node->accept(*this);
        this->in_edge_stack.pop();
    }

    shared_ptr<LoopExit> loop_exit;
    if (loop_mode == LoopMode::WHILE) {
        loop_exit = dynamic_pointer_cast<LoopExit>(loop_if_node->branch_false());
    }
    else {
        loop_exit = dynamic_pointer_cast<LoopExit>(for_in_enum_node->branch_false());
    }
    assert_or_throw_graph2js((loop_exit != nullptr),
        "No Loop Exit node");

    /// After the loop exit, a new region is required
    this->current_region_single = nullptr;

    walk_along_uniSuccessor(loop_exit);
}

void JavaScriptLifter::visit(shared_ptr<IfNode> &node)
{
    if (dynamic_pointer_cast<LoopIf>(node) != nullptr) {
        return;
    }

    this->check_region_single();

    auto region_if = make_shared<RegionIfNode>();
    this->current_parent_region->add_region(region_if);
    region_if->post_construct();

    /// save parent region
    auto parent_region = this->current_parent_region;

    /// Lift the condition data flow
    this->in_edge_stack.push(InEdgeType::Data);
    node->condition()->accept(*this);
    this->in_edge_stack.pop();

    const string condition_code = visit_outcome;
    region_if->condition->emit_expression(condition_code);

    /// lift the true branch
    /// Traversing to the EndNode indicates the end of the branch and the traversal stops.
    this->current_parent_region = region_if->branch_true;

    auto region_single_true = make_shared<RegionSingle>();
    region_if->branch_true->add_region(region_single_true);
    this->current_region_single = region_single_true;

    this->in_edge_stack.push(InEdgeType::Ctrl);
    node->branch_true()->accept(*this);
    this->in_edge_stack.pop();

    shared_ptr<CtrlRelayNode> true_relay_node = nullptr;
    shared_ptr<AbstractMergeNode> true_merge_node = nullptr;

    true_merge_node = this->get_merge_node();
    if (true_merge_node == nullptr) {
        /// When merge node is null, two scenarios are possible:
        /// 1. True branch ends with throw (no subsequent control flow)
        /// 2. True branch ends normally but false branch doesn't,
        ///    resulting in no merge node. In this case, true branch
        ///    connects forward via a control relay node.
        ///
        /// Note: The following line attempts to query the relay node,
        ///       which may return null.
        true_relay_node = this->get_relay_node();
    }

    /// lift the false branch
    /// Traversing to the EndNode indicates the end of the branch and the traversal stops.
    this->current_parent_region = region_if->branch_false;

    const auto region_single_false = make_shared<RegionSingle>();
    region_if->branch_false->add_region(region_single_false);
    this->current_region_single = region_single_false;

    this->in_edge_stack.push(InEdgeType::Ctrl);
    node->branch_false()->accept(*this);
    this->in_edge_stack.pop();

    shared_ptr<CtrlRelayNode> false_relay_node = nullptr;
    const shared_ptr<AbstractMergeNode> false_merge_node = this->get_merge_node();
    if (false_merge_node == nullptr) {
        false_relay_node = this->get_relay_node();
    }

    if (true_merge_node != nullptr) {
        /// handling the phi node of the merge
        for (const auto& phi_node : true_merge_node->phi_nodes()) {
            /// TODO:
            /// gecko-dev_js_src_jit-test_tests_auto-regress_bug679799.js
            if (! phi_node.lock()->inputs.empty()) {
                this->current_region_single = region_single_true;
                auto _node = phi_node.lock()->get_input(0);

                this->in_edge_stack.push(InEdgeType::Data);
                _node->accept(*this);
                this->in_edge_stack.pop();
            }

            if (phi_node.lock()->inputs.size() > 1) {
                this->current_region_single = region_single_false;
                auto _node = phi_node.lock()->get_input(1);

                this->in_edge_stack.push(InEdgeType::Data);
                _node->accept(*this);
                this->in_edge_stack.pop();
            }
        }
    }

    /// restore parent region
    this->current_parent_region = parent_region;

    /// Just ended a RegionIfNode. We need to create a new Region
    this->current_region_single = nullptr;

    check_region_single();

    ASSERT_OR_EXIT(this->last_merge_node == nullptr);
    ASSERT_OR_EXIT(this->last_relay_node == nullptr);

    ///
    /// Continue traversing along the control flow
    ///
    /// Three termination scenarios for branches:
    ///  1. Both branches end normally - continue after MergeNode
    ///  2. One branch ends normally, the other throws - continue after normal termination
    ///     (marked by CtrlRelayNode in graph)
    ///  3. Both branches throw - no further traversal needed (handled by try-catch-finally)
    ///
    if (dynamic_pointer_cast<MergeNode>(true_merge_node)) {
        /// scenario 1
        walk_along_uniSuccessor(true_merge_node);
    }
    else if (dynamic_pointer_cast<CtrlRelayNode>(true_relay_node)
        || dynamic_pointer_cast<CtrlRelayNode>(false_relay_node))
    {
        /// scenario 2
        if (true_relay_node) {
            walk_along_uniSuccessor(true_relay_node);
        }
        else {
            walk_along_uniSuccessor(false_relay_node);
        }
    }
    else {
        /// scenario 3
        return;
    }
}

void JavaScriptLifter::visit(shared_ptr<BeginNode> &node)
{
    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::visit(shared_ptr<ReturnNode> &node)
{
    this->check_region_single();

    string return_value;

    if (const auto node_opt = node->return_value()) {
        if (node_opt.has_value()) {
            this->in_edge_stack.push(InEdgeType::Data);
            node_opt.value()->accept(*this);
            this->in_edge_stack.pop();

            return_value = visit_outcome;
        }
    }

    this->current_region_single->emit_return(return_value);
}

string JavaScriptLifter::get_invoke_expr(const string& function_name,
                                         const vector<string> &arg_names,
                                         const bool new_constructor)
{
    string invoke_stmt;

    if (new_constructor) {
        invoke_stmt += "new ";
    }

    invoke_stmt += function_name + "(";

    for (int i = 0; i < arg_names.size(); i++) {
        if (i == 0) {
            invoke_stmt += arg_names[i];
        }
        else {
            invoke_stmt += "," + arg_names[i];
        }
    }
    invoke_stmt += ")";

    return invoke_stmt;
}

void JavaScriptLifter::visit(shared_ptr<InvokeNode> &node)
{
    this->check_region_single();

    vector<string> arg_names;

    if (const auto call_args = node->get_args();
        ! call_args.empty())
    {
        for (auto &arg_node : call_args) {
            in_edge_stack.push(InEdgeType::Data);
            arg_node.lock()->accept(*this);
            in_edge_stack.pop();

            string arg_code = visit_outcome;
            arg_names.push_back(arg_code);
        }
    }

    const string func_name = node->get_function_name();

    const vector<shared_ptr<VarSymbol>> var_syms = this->get_varSymbols_on_producer(node);

    const bool isVarProxiesFullyAssigned = this->all_varProxy_available(node);

    const InvokeType invoke_type = node->get_invoke_type();
    const bool new_constructor = (invoke_type == InvokeType::NewInstance) ? true : false;
    const string invoke_expr = get_invoke_expr(func_name, arg_names, new_constructor);

    string var_proxy_name;

    if (! var_syms.empty()) {
        var_proxy_name = var_syms[0]->name;
    }

    if (! isVarProxiesFullyAssigned) {
        this->gen_assignment_for_producer(node, invoke_expr, false);
    }

    /// Check whether there is any data flow nodes (excluding fixed LoadNode) that depends
    /// on the load producer. If true, assignment statement is needed.
    const bool is_used = ! node->uses.empty();

    if (! var_proxy_name.empty()) {
        visit_outcome = var_proxy_name;
    }
    else if (is_used) {
        /// There is no var proxy on this floating node, return the expression
        visit_outcome = invoke_expr;
    }
    else {
        /// No attached var proxy, no usage by other data, we just create a invoke statement
        this->current_region_single->emit_invoke(invoke_expr);
        ///  now, we do not need visit outcome
    }

    if (in_edge_stack.top() == InEdgeType::Ctrl) {
        walk_along_uniSuccessor(node);
    }
}

void JavaScriptLifter::visit(shared_ptr<InvokeMethodNode> &node)
{
    this->check_region_single();

    vector<string> arg_names;

    if (const auto call_args = node->get_args();
        ! call_args.empty())
    {
        for (auto &arg_node : call_args) {
            this->in_edge_stack.push(InEdgeType::Data);
            arg_node.lock()->accept(*this);
            this->in_edge_stack.pop();

            string arg_code = visit_outcome;
            arg_names.push_back(arg_code);
        }
    }

    this->in_edge_stack.push(InEdgeType::Data);
    node->get_load_node()->accept(*this);
    this->in_edge_stack.pop();

    const auto load_method_expr = visit_outcome;

    const vector<shared_ptr<VarSymbol>> var_syms = this->get_varSymbols_on_producer(node);

    const bool isVarProxiesFullyAssigned = this->all_varProxy_available(node);

    const string invoke_expr = get_invoke_expr(load_method_expr, arg_names, false);

    string var_proxy_name;

    if (!var_syms.empty() && !isVarProxiesFullyAssigned) {
        this->gen_assignment_for_producer(node, invoke_expr, false);
        var_proxy_name = var_syms[0]->name;
    }

    /// Check whether there is any data flow nodes (excluding fixed LoadNode) that depends
    /// on the load producer. If true, assignment statement is needed.
    const bool is_used = ! node->uses.empty();

    if (! var_proxy_name.empty()) {
        visit_outcome = var_proxy_name;
    }
    else if (is_used) {
        /// There is no var proxy on this floating node, return the expression
        visit_outcome = invoke_expr;
    }
    else {
        /// No attached var proxy, no usage by other data, we just create a invoke statement
        this->current_region_single->emit_invoke(invoke_expr);
        ///  now, we do not need visit outcome
    }

    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::walk_along_uniSuccessor(const shared_ptr<UniSuccessorNode> &node)
{
    if (this->in_edge_stack.top() != InEdgeType::Ctrl) {
        return;
    }

    this->check_region_single();

    auto [it, insertion_done] = visited_fixed.insert(node);

    if (insertion_done) {
        this->in_edge_stack.push(InEdgeType::Ctrl);
        node->next()->accept(*this);
        this->in_edge_stack.pop();
    }
}

void JavaScriptLifter::visit(shared_ptr<StoreNode> &node)
{
    this->check_region_single();

    string store_code;

    this->in_edge_stack.push(InEdgeType::Data);
    node->object()->accept(*this);
    this->in_edge_stack.pop();

    const string object_code = visit_outcome;

    this->in_edge_stack.push(InEdgeType::Data);
    node->property()->accept(*this);
    this->in_edge_stack.pop();

    const string property_name_code = visit_outcome;

    this->in_edge_stack.push(InEdgeType::Data);
    node->new_value()->accept(*this);
    this->in_edge_stack.pop();

    const string property_value_code = visit_outcome;

    bool self_assignment = false;
    if (const auto binary_op = dynamic_pointer_cast<BinaryOpNode>(node->new_value())) {
        if (OperatorPairs::assignment_op.contains(binary_op->op->code)) {
            self_assignment = true;
        }
    }

    this->current_region_single->emit_store(object_code,
                                            property_name_code,
                                            property_value_code,
                                            node->access_type,
                                            self_assignment);

    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::visit(shared_ptr<LoadNode> &node)
{
    this->check_region_single();

    const bool is_first_visit = ! visited_nodes.contains(node);

    if (is_first_visit) {
        visited_nodes.insert(node);
    }

    const vector<shared_ptr<VarSymbol>> var_syms = this->get_varSymbols_on_producer(node);

    string load_expr_code;

    const bool isVarProxiesFullyAssigned = this->all_varProxy_available(node);

    if (is_first_visit || var_syms.empty() || (!isVarProxiesFullyAssigned)) {
        /// Generate the load expression.

        this->in_edge_stack.push(InEdgeType::Data);
        node->object()->accept(*this);
        this->in_edge_stack.pop();

        const string object_code = visit_outcome;

        this->in_edge_stack.push(InEdgeType::Data);
        node->property()->accept(*this);
        this->in_edge_stack.pop();

        const string property_name_code = visit_outcome;

        if (node->access_type == ObjectAccessType::field) {
            load_expr_code = object_code + "." + property_name_code;
        }
        else {
            load_expr_code = object_code + "[" + property_name_code + "]";
        }
    }

    string var_proxy_name;

    if (!var_syms.empty() && !isVarProxiesFullyAssigned) {
        this->gen_assignment_for_producer(node, load_expr_code, false);
        var_proxy_name = var_syms[0]->name;
    }

    /// Check whether there is any data flow nodes (excluding fixed LoadNode) that depends
    /// on the load producer. If true, assignment statement is needed.
    const bool is_used = ! node->uses.empty();

    if (! var_proxy_name.empty()) {
        visit_outcome = var_proxy_name;
    }
    else if (is_used) {
        /// There is no var proxy on this floating node, return the expression
        visit_outcome = load_expr_code;
    }
    else {
        /// No attached var proxy, no usage by other data, we just create a load statement
        this->current_region_single->emit_load(load_expr_code);

        ///  now, we do not need visit outcome
    }

    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::visit(shared_ptr<DeleteNode> &node)
{
    this->check_region_single();

    const shared_ptr<DataProducerNode> del_tgt_node = node->del_tgt();

    this->in_edge_stack.push(InEdgeType::Data);
    del_tgt_node->accept(*this);
    this->in_edge_stack.pop();

    const string del_tgt_expr = visit_outcome;

    /// Check if the DeleteNode has an attached var proxy. If so, an assignment statement needs to be generated.
    const vector<shared_ptr<VarProxy> > attached_proxies = this->get_varProxies_on_producer(node);

    const string del_expr = "delete " + del_tgt_expr;

    if (const bool is_used = ! node->uses.empty();
        is_used && attached_proxies.empty())
    {
        /// No `var proxy` means the expression result is not stored in a variable.
        /// If the node is still used as input by other nodes, it is being used directly as an expression.
        /// In this case, the `Delete` node should be used by only one data flow edge.
        ///
        /// If reached via control flow, the `visit outcome` is not used.
        /// The `outcome` here is only relevant when reached via a data flow edge.
        visit_outcome = del_expr;
    }
    else if (! attached_proxies.empty()) {
        /// If an attached var proxy exists, generate an assignment statement based on the var proxy.
        this->gen_assignment_for_producer(node, del_expr, false);
    }
    else {
        /// If there is no attached var proxy and the node is not used as data input for other nodes,
        /// only a DeleteExpression statement needs to be generated.
        this->current_region_single->emit_delete(del_expr);
    }

    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::visit(shared_ptr<TryNode> &node)
{
    this->check_region_single();

    bool has_catch = false;
    bool has_finally = false;

    const auto catch_node = node->catch_node.lock();
    const auto finally_node = node->finally_node.lock();

    if (! node->catch_node.expired()) {
        has_catch = true;
    }

    if (! node->finally_node.expired()) {
        has_finally = true;
    }

    const auto region_try = make_shared<RegionTry>(has_catch, has_finally);

    /// First, set the parent of `RegionTry`, then call its post-construction handler.
    this->current_parent_region->add_region(region_try);
    region_try->post_construct();

    this->try2parentRegions.push_back({node, this->current_parent_region});

    /// interpret try block
    this->current_parent_region = region_try->try_block;
    const auto region_single_in_try = make_shared<RegionSingle>();
    this->current_region_single = region_single_in_try;
    this->current_parent_region->add_region(region_single_in_try);

    shared_ptr<AbstractMergeNode> try_merge_node = nullptr;
    walk_along_uniSuccessor(node);
    try_merge_node = this->get_merge_node();

    shared_ptr<AbstractMergeNode> catch_end_merge_node = nullptr;

    /// interpret catch expr
    if (catch_node != nullptr) {
        if (catch_node->opt_catch_id_node.has_value()) {
            auto catch_id_node = catch_node->opt_catch_id_node.value();

            this->in_edge_stack.push(InEdgeType::Data);
            catch_id_node.lock()->accept(*this);
            this->in_edge_stack.pop();

            string condition_expr = this->visit_outcome;
            region_try->catch_expr->emit_expression(condition_expr);
        }
    }

    shared_ptr<AbstractMergeNode> catch_merge_node = nullptr;

    /// interpret catch block
    if (catch_node != nullptr) {
        this->current_parent_region = region_try->catch_block;
        const auto region_single_in_body = make_shared<RegionSingle>();
        this->current_region_single = region_single_in_body;
        this->current_parent_region->add_region(region_single_in_body);

        walk_along_uniSuccessor(catch_node);
        catch_merge_node = this->get_merge_node();
    }

    /// traverse finally block
    if (finally_node != nullptr) {
        this->current_parent_region = region_try->finally_block;
        auto region_single_in_body = make_shared<RegionSingle>();
        this->current_region_single = region_single_in_body;
        this->current_parent_region->add_region(region_single_in_body);

        walk_along_uniSuccessor(finally_node);
    }

    if (! this->try2parentRegions.empty()) {
        auto _try_node_w = this->try2parentRegions.back().first;
        if (node == _try_node_w.lock()) {
            this->current_parent_region = this->try2parentRegions.back().second;
            this->try2parentRegions.pop_back();

            this->current_region_single = nullptr;
            check_region_single();
        }
    }

    if ((try_merge_node != nullptr) && (catch_merge_node != nullptr)) {
        walk_along_uniSuccessor(try_merge_node);
    }
}

void JavaScriptLifter::visit(shared_ptr<UnwindNode> &node)
{
    this->check_region_single();

    string throw_value;
    if (const auto exception_node = node->exception_node())
    {
        this->in_edge_stack.push(InEdgeType::Data);
        exception_node->accept(*this);
        this->in_edge_stack.pop();

        throw_value = visit_outcome;
    }

    this->current_region_single->emit_throw(throw_value);
}

void JavaScriptLifter::visit(shared_ptr<TryExit> &node)
{
    ASSERT_OR_EXIT(! this->try2parentRegions.empty());
    this->current_parent_region = this->try2parentRegions.back().second;
    this->try2parentRegions.pop_back();

    this->current_region_single = nullptr;
    this->check_region_single();

    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::visit(shared_ptr<ForInEnum> &node)
{
    this->check_region_single();

    const auto region_if = make_shared<RegionIfNode>();
    this->current_parent_region->add_region(region_if);
    region_if->post_construct();
}

/// ------------ data producers ------------

void JavaScriptLifter::visit(const shared_ptr<DataProducerNode> &node)
{
    const vector<shared_ptr<VarSymbol>> attached_vars = this->get_varSymbols_on_producer(node);

    const auto has_visited = visited_nodes.contains(node);

    const bool isVarProxiesFullyAssigned = this->all_varProxy_available(node);

    string producer_expr;

    if (!has_visited || attached_vars.empty() || !isVarProxiesFullyAssigned) {
        /// Cases requiring traversal of both child nodes:
        ///
        /// 1. First visit to this node
        /// 2. Node contains no attached variables (returns expression)
        /// 3. Var proxy on node is unreachable in current scope
        ///     (previous assignment was generated in narrower scope)
        ///
        visited_nodes.insert(node);

        this->in_edge_stack.push(InEdgeType::Data);
        producer_expr = node->get_producer_expr(*this);
        this->in_edge_stack.pop();
    }

    bool self_assignment = false;
    if (const auto binary = dynamic_pointer_cast<BinaryOpNode>(node)) {
        if (OperatorPairs::assignment_op.contains(binary->op->code)) {
            self_assignment = true;
        }
    }

    if ((!attached_vars.empty()) && (!isVarProxiesFullyAssigned)) {
        // When attached var proxies exist but aren't all accessible in current region,
        // we need to generate assignments for them.
        this->gen_assignment_for_producer(node, producer_expr, self_assignment);
    }

    if (!attached_vars.empty()) {
        visit_outcome = attached_vars[0]->name;
    }
    else {
        visit_outcome = producer_expr;
    }
}

void JavaScriptLifter::visit(shared_ptr<ParameterNode> &node)
{
    const string param_name = node->get_parameter_name();
    visit_outcome = param_name;
}

void JavaScriptLifter::visit(shared_ptr<CatchIdNode> &node)
{
    const string id_name = node->get_id_name();
    visit_outcome = id_name;
}

void JavaScriptLifter::visit(shared_ptr<LiteralBoolNode> &node)
{
    const shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);
    visit(producer);
}

void JavaScriptLifter::visit(shared_ptr<LiteralFloatNode> &node)
{
    const shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);
    visit(producer);
}

void JavaScriptLifter::visit(shared_ptr<LiteralStringNode> &node)
{
    const shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);
    visit(producer);
}

void JavaScriptLifter::visit(shared_ptr<GlobalVarNode> &node)
{
    const shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);
    visit(producer);
}

void JavaScriptLifter::visit(shared_ptr<GlobalFunctionNode> &node)
{
    const shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);
    visit(producer);
}

/// When lifting encounters a merge node, it directly lifts the phi node's inputs
/// instead of invoking the phi node's lift function
///
/// The phi node's lift function is only called when the phi itself serves as
/// input to other consumers
///
void JavaScriptLifter::visit(shared_ptr<PhiNode> &node)
{
    if (const vector<shared_ptr<VarSymbol>> var_syms = get_varSymbols_on_producer(node);
        !var_syms.empty())
    {
        visit_outcome = var_syms[0]->name;
        return;
    }

    /// Code generation for phi nodes is already handled at `IfNode` and `LoopBegin`.
    /// Here, we only need to return the variable name associated with the phi node.
    const shared_ptr<VarSymbol> var_sym = get_phi_main_proxy(node);
    visit_outcome = var_sym->name;
}

void JavaScriptLifter::visit(shared_ptr<BinaryOpNode> &node)
{
    const shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);

    visit(producer);

    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::visit(shared_ptr<UnaryOpNode> &node)
{
    shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);

    visit(producer);

    walk_along_uniSuccessor(node);
}

void JavaScriptLifter::visit(shared_ptr<TernaryOpNode> &node)
{
    shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);

    visit(producer);
}

void JavaScriptLifter::visit(shared_ptr<PropExprAssignNode> &node)
{
    this->in_edge_stack.push(InEdgeType::Data);
    node->property_name()->accept(*this);
    this->in_edge_stack.pop();

    const string prop_name_code = visit_outcome;

    this->in_edge_stack.push(InEdgeType::Data);
    node->property_value()->accept(*this);
    this->in_edge_stack.pop();

    const string prop_value_code = visit_outcome;

    visit_outcome = prop_name_code + ":" + prop_value_code;
}

void JavaScriptLifter::visit(shared_ptr<FunctionPropertyNode> &node)
{
    const shared_ptr<DataProducerNode> prop_name_node = node->property_name();

    this->in_edge_stack.push(InEdgeType::Data);
    prop_name_node->accept(*this);
    this->in_edge_stack.pop();

    string prop_name = visit_outcome;

    auto method_graph = node->function_graph.lock();

    /*
     * TODO:
     * gecko-dev_js_src_jit-test_tests_warp_store-element-hole-sparse-element.js
     */
    if (method_graph == nullptr) {
        throw LiftError("null function prop graph");
    }

    JavaScriptLifter method_lifter(method_graph);
    method_lifter.lift();

    ScriptWriter script_writer;
    const string literal_code = script_writer.emit_method(method_lifter.function_args, method_lifter.top_region);

    visit_outcome = prop_name + literal_code + ",";
}

void JavaScriptLifter::visit(shared_ptr<ObjectLiteralNode> &node)
{
    shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);

    visit(producer);
}

void JavaScriptLifter::visit(shared_ptr<BuiltinNode> &node)
{
    visit_outcome = node->get_label();
}

void JavaScriptLifter::visit(shared_ptr<ThisNode> &node)
{
    visit_outcome = "this";
}

void JavaScriptLifter::visit(shared_ptr<ArrayLiteralNode> &node)
{
    shared_ptr<DataProducerNode> producer = static_pointer_cast<DataProducerNode>(node);

    visit(producer);
}

void JavaScriptLifter::visit(shared_ptr<ForInPropName> &node)
{
    visit_outcome = node->prop_name;
}

} /// end of namespace